### PR TITLE
Updates

### PR DESCRIPTION
**Pull request by ramonvic**
Updates and new features

### CODE REVIEW

**Comment by benwilkins** [comment]
With regards to the class names, PSR coding standards require class names be StudlyCase. Typically this includes acronyms and abbreviations. This is precedent in Laravel, also. (Class `Illuminate\Mail\Transport\SesTransport`) See here for more info http://www.php-fig.org/psr/psr-1/#overview.

Please revert the class name changes, or provide an example in Laravel where it shows otherwise.

**Comment by ramonvic** [comment]
I returned the class names to StudlyCase. I agree with your suggestion.

**Comment by tusharvikky** [comment]
Any update on the merge? Would love to have the functionality to send array to routeNotificationForFcm so that we can send a notification to multiple devices of a user.

**Comment by benwilkins** [comment]
Sorry for the delay. I'll review this tonight.

**Comment by tusharvikky** [comment]
Update?

**Pull request merged**
