### PR TITLE
Allow laravel 7.x

### PR DESCRIPTION
**Pull request by sonnysantino**
Allow laravel 7.x

---
This change is [Reviewable](https://reviewable.io/reviews/benwilkins/laravel-fcm-notification/56)

### CODE REVIEW

**Comment by maherelgamil** [comment]
any updates here?

**Comment by ankurk91** [comment]
@santiripper 

The composer.json should be updated like
```
"~5.3||^6.0||^7.0"
```

It should support 5.x, 6.x and 7.x

**Comment by sonnysantino** [comment]
Updated, thanks @ankurk91

**Comment by ankurk91** [comment]
ping @benwilkins

**Comment by ankurk91** [comment]
@benwilkins
Please tag a new patch version. Thanks!

**Pull request merged**
