### PR TITLE
Update FcmChannel.php

### PR DESCRIPTION
**Pull request by mgralikowski**
I would to prevent call code in toFcm because is little expensive (many relations loaded to get message content) if notifiable (User in my case) has disabled notifications or he never logged into app.

```php
    /**
     * @param  User $notifiable
     * @return FcmMessage
     */
    public function toFcm($notifiable)
    {
        if ($notifiable->shouldBeNotified()) {

            $fcmData = [
                'id'              => $this->message->id,
                // and lot of stuff (many relations)
            ];
            $message = (new FcmMessage())->data($fcmData);
            $message->priority(FcmMessage::PRIORITY_HIGH);
            return $message;

        }

        return new FcmMessage; // null or false more readable? 
    }
```

### CODE REVIEW

**Comment by VladimirBerdnik** [comment]
Hi! maybe I missed something, but we already can do it in `via` method or in `routeNotificationForFcm` method - just return null from there and `toFcm` even not be called

**Comment by mgralikowski** [comment]
Sure, it's a way to prevent send a fcm notification:

```php
    public function routeNotificationForFcm()
    {
        return $this->shouldBeNotified() ? $this->apiAccess->app_token : null;
    }
```
but it dosen't stop calling toFcm() method because toFcm is called in Your library as first.

Anyway i try with "via" method.

**Comment by mgralikowski** [comment]
Ok, You are right.

```php
    /**
     * Get the notification's delivery channels.
     *
     * @param  User  $notifiable
     * @return array
     */
    public function via($notifiable)
    {
        return $notifiable->shouldBeNotified() ? ['fcm'] : [];
    }
```
is much cleaner solution.

**Comment by VladimirBerdnik** [comment]
what if we return empty array from `via`? actually it's not my library) I just want to help

**Comment by VladimirBerdnik** [comment]
yep, my answer was too late, sorry, I typed from mobile)

**Pull request closed without merging**
